<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNtrjlqa\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNtrjlqa/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNtrjlqa.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNtrjlqa\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerNtrjlqa\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Ntrjlqa',
    'container.build_id' => '927ad4b9',
    'container.build_time' => 1538619884,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerNtrjlqa');
